### ISSUE TITLE
Compile button

### ISSUE THREAD

**Issue by regs01** [idleberg/vscode-nsis#1]
Is it possible to make something to quickly compile nsi from under VS.C?

**Comment by idleberg** [comment]
I'm definitely interested to add build support, like in my [Atom package](https://github.com/idleberg/atom-language-nsis), but I'll have to dig in to the API docs when I have more time for it.

**Comment by idleberg** [comment]
The master now contains *very* rudimentary build support, I'll keep working on it over the next days or so.

I did some research on buttons, but it seems there is currently no way to add buttons to the sidebar. Just use the shortcut!

**Comment by idleberg** [comment]
Building capability is now officially part of the extension, see the [README](https://github.com/idleberg/vscode-nsis#building) for details!
