### ISSUE TITLE
Compile only shows help

### ISSUE THREAD

**Issue by ukandrewc** [idleberg/vscode-nsis#11]
Nothing has changed with my setup, this used to work.
Calls makeNSIS, but doesn't compile, only shows help in log:

_MakeNSIS v2.46 - Copyright 1995-2009 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Usage:
  makensis [option | script.nsi | - [...]]_

**Comment by ukandrewc** [comment]
Reverted to V3.16.0 which works.

**Comment by idleberg** [comment]
It would be helpful if you could provide more useful information, e.g. operating system, how you installed NSIS, any special settings for this extension.

**Comment by ukandrewc** [comment]
Hi
Windows 7 32bit, installed using Extensions in VS Code.
Sorry, no any errors, just the makensis output,
I assumed the command line had changed.
As I say, reverting to revision V3.16.0 works again.
I hadn't changed any settings, just installed the older version.
I can test a debug version if you need.

**Comment by idleberg** [comment]
The only major change in recent versions is how compiler arguments are handled. Could you please verify the settings for those are in order?

**Comment by ukandrewc** [comment]
I haven't changed these since installing over a year ago:

"nsis.compilerArguments": "/P4 /V3"
"nsis.nsl.customArguments": "/nomake /nopause"

It's certainly the command line that has changed, but I don't know how to see that from VS Code.

**Comment by idleberg** [comment]
As mentioned before, the format for `compilerArguments` has changed. Please try the following:

```"nsis.compilerArguments": ["/P4", "/V3"]
"nsis.nsl.customArguments": ["/nomake", "/nopause"]
```

**Comment by ukandrewc** [comment]
I see, thanks, I thought you meant internal to the code.
