### ISSUE TITLE
Pressing "Run" after compiling script has no effect

### ISSUE THREAD

**Issue by iansan5653** [idleberg/vscode-nsis#12]
Pressing "Run" in this box has no effect:

![image](https://user-images.githubusercontent.com/2294248/68076828-7a457100-fd90-11e9-9826-eb0f81a2b17c.png)

Pressing "Reveal" works as expected though.

System info:
Version: 1.40.0-insider (system setup)
Commit: 29ffbfe3f1c21b01a2d0670170855669dd2b3b4f
Date: 2019-10-25T14:03:31.497Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by idleberg** [comment]
Which version of the extension are you using? Is there an error in VSCode's Developer Tools?

**Comment by iansan5653** [comment]
I'm using `3.20.3`.

There is an error in the devtools. Source is `log.ts:196`:

>   ERR spawn c:\Users\Ian Sanders\Git Repositories\scantron-reading\bubble_sheet_reader_install.exe EACCES: Error: spawn c:\Users\Ian Sanders\Git Repositories\scantron-reading\bubble_sheet_reader_install.exe EACCES
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
> 	at onErrorNT (internal/child_process.js:456:16)
> 	at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by idleberg** [comment]
I believe this is an issue with UAC, so I'm going to assume your installer uses `RequestExecutionLevel admin` or `highest`. This should be fixed in `v3.20.4` 🤞

**Comment by iansan5653** [comment]
Yep, my installer does currently request admin privileges. Thanks!

**Comment by idleberg** [comment]
Thanks for reporting the issue (let me know if the update works for you!). I'm developing on a Mac mostly, so I didn't run into this before.
