### ISSUE TITLE
NSIS can't find install even with it is in PATH environment variable

### ISSUE THREAD

**Issue by dshewmaker** [idleberg/vscode-nsis#14]
I had to add to the user settings but verified makensis was in the path and showed up with the powershell command PS D:\>Get-ChildItem Env: on Windows 10

I tried it as user and system variables and both upper and lowercase and rebooted.

Perhaps just removing the mention of the PATH variable and just have users add to settings.json would be best. Or set in for them during the extension install. Either Code or NSIS does not appear to read the path variable.

**Comment by idleberg** [comment]
It would be helpful to know what exactly you added to your `PATH`
