### ISSUE TITLE
Syntax highlighting not working since latest VS Code update.

### ISSUE THREAD

**Issue by bhair** [idleberg/vscode-nsis#17]
It would seem that since updating to the latest VS Code that my NSIS syntax highlighting is not working as it used to as shown in this image:
![image](https://user-images.githubusercontent.com/38145576/82245141-0a4fa000-9908-11ea-9379-13a934d5f223.png)

Normally the quoted strings and commands like "File" and "!include" are highlighted, but they are not anymore. It seems to be a limited set of things that are syntax highlighted now.

Here is information about VS Code version:
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Is there more information that you need?

**Comment by idleberg** [comment]
This package has been using the TextMate/Sublime Text grammar syntax from its very start. Apparently, VSCode's syntax highlighter –with interprets the TextMate format– was replaced in the [April 2020](https://code.visualstudio.com/updates/v1_45#_faster-syntax-highlighting) update. 

I'd argue, that the new interpreter isn't working *exactly* the same as TextMate or Sublime Text. Even if there was a bug in the NSIS syntax definition (which I cannot rule out), I'd expect VSCode syntax interpreter to work the same as for those others editors – with all its quirks.

**Comment by idleberg** [comment]
This is the portion of the syntax grammar that is now broken: https://github.com/idleberg/vscode-nsis/blob/044253ea0f0c9557af629bc545d1eb54312820d7/syntaxes/nsis.tmLanguage#L167-L373

**Comment by bhair** [comment]
Thanks, will do.

Can you point me in the correct direction for where I should report that at then? I'm not sure where to go for the VS Code end of this I guess.

**Comment by idleberg** [comment]
I've found the repository for the highlighter is [vscode-oniguruma](https://github.com/microsoft/vscode-oniguruma). However, since the release notes for the April 2020 update link to this [pull-request](https://github.com/microsoft/vscode/pull/95958), I guess it's fine to report the issue in that repository.

**Comment by bhair** [comment]
Thanks, I'll pursue submitting this against VS Code and see where we get.

**Comment by bhair** [comment]
Perhaps this can provide some insight?

There is another NSIS syntax highlighting extension that does appear to work in the new VS Code version called "NSIS Language Support" whose code is here: https://gitlab.com/krystofriha/vscode-nsis

They claim theirs is based on this project: https://github.com/SublimeText/NSIS

No idea if they are following a similar path as you or if that helps, but it works so thought it might provide insight as to what might be going on further?

**Comment by idleberg** [comment]
> They claim theirs is based on this project: SublimeText/NSIS

Both packages are based on that. The difference being, that this extension has been updated along the Sublime package, which Krsytof's version hasn't received any updates since 2016. It was later in 2016, that variable highlighting inside strings has been added to both, the Sublime package and my NSIS extension.

**Comment by idleberg** [comment]
I've tracked down the pattern that no longer work in VSCode v1.45:

```xml
<dict>
	 <key>match</key>
	<string>((((https?|ftps?):(?:\/\/))(?:[-;:&amp;=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&amp;=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&amp;%@.\w_]*)#?(?:[\w]*))?)</string>
	<key>name</key>
	<string>markup.underline.link.nsis</string>
</dict>
```

Given that VSCode already highlights URLs, I guess we can safely remove these patterns from the syntax definition.

**Comment by idleberg** [comment]
Fixed in `v3.27.0`

**Comment by bhair** [comment]
Cool! Glad you were able to find it.

How long does it normally take for your updated versions to trickle through the VS Code extension system for me to get the update?

Also, the nuanced syntax highlighting within strings has been a major help of your plugin in reading through my NSIS code. Thanks for creating a great VS Code extension!

**Comment by bhair** [comment]
Just wanted to confirm with you that it does indeed appear to be working again, thanks!
![image](https://user-images.githubusercontent.com/38145576/82710783-5d4b8f00-9c49-11ea-8bb5-b693fad47b91.png)

I can't remember if they were highlighted previously, is it expected for things like "${VC_RUNTIME_YEAR}" to not be highlighted in strings? I feel like they might have been previously but I can't be certain on that.

**Comment by idleberg** [comment]
> I can't remember if they were highlighted previously, is it expected for things like "${VC_RUNTIME_YEAR}" to not be highlighted in strings? I feel like they might have been previously but I can't be certain on that.

It's highlighted, but not all themes might support this. For example, it works fine in *Dark+* but not in *Dark*. The reason is the interplay between language grammar and a theme: the former defines syntax rules that *can* then be highlighted uses the latter.

**Comment by bhair** [comment]
Ah, I see that now. Interesting, I didn't know there was that interplay between the themes and the language grammar. 

I see it work in Solarized Dark but neither Dark nor Dark+. I'll find another theme to use for NSIS, thanks.

**Comment by bhair** [comment]
Just wanted to make sure you saw the VS Code feedback on their ticket, they had the following to say:

> To be more precise, this construct is the root cause:
> 
>` [\+~%\/.\w-_]`
> 
> In the latest version of oniguruma, parsing the regular expression throws unmatched range specifier in char-class from oniguruma. Perhaps the newer version of oniguruma is more strict around this ambiguous `-`. The solution is to escape `-` with `\-`:
> 
> `[\+~%\/.\w\-_]`
> 
> Given that idleberg/vscode-nsis#17 has removed the rule entirely, I don't think there is any further need to do anything. We could potentially ask at https://github.com/kkos/oniguruma if this was intentional or not, but I leave that to you.

https://github.com/microsoft/vscode-oniguruma/issues/2
