### ISSUE TITLE
Remove IBM Output Colorizer dependency

### ISSUE THREAD

**Issue by kenijo** [idleberg/vscode-nsis#18]
Could you remove the dependency to the IBM Output Colorizer since it hasn't been updated in 3 years? https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

Or at least move to a different package that is actively maintained such as Logfile Highlighter? https://github.com/emilast/vscode-logfile-highlighter

The IBM Output Colorizer breaks some of my other extensions and in order to remove it, I have to get rid of NSIS and NSIS-Plugins.

**Comment by idleberg** [comment]
I will consider this, but until you can simply deactivate the IBM Output Colorizer extension

**Comment by kenijo** [comment]
You actually cannot disable the IBM Output Colorizer without disabling the NSIS.
See screenshot below:
![Image 002](https://user-images.githubusercontent.com/5394591/82473097-ee6e0a80-9a7d-11ea-9564-723c40a2e164.png)

**Comment by idleberg** [comment]
I've removed the dependency *IBM Output Colorizer* since it was a highly opinionated feature that might not work others. Please update to `v3.27.0`and thanks again for bringing this up.

**Comment by kenijo** [comment]
Awesome! Thank you
