### ISSUE TITLE
NSISCONFDIR environment variable not available

### ISSUE THREAD

**Issue by wfmw445** [idleberg/vscode-nsis#20]
When using 'NSIS: Save & Compile' the NSISCONFDIR environment variable is not recognized.
Instead I have to use tasks.json. My NSISCONFDIR is pointing to a path relative to the current working directory.

**Comment by idleberg** [comment]
Can you please check whether the latest master works for you as desired?

**Comment by wfmw445** [comment]
I’m new to vs-code + extensions.
Following the guide on GitHub with ‚git clone…‘ and 'cd nsis && npm install'

After restarting vs-code and executing build I got:
Command 'NSIS: Save & Compile Script' resulted in an error (command 'extension.nsis.compile' not found)

Please advice

**Comment by idleberg** [comment]
You could open the [Developer Tools](https://stackoverflow.com/questions/30765782/what-is-the-use-of-the-developer-tools-in-vs-code) console to see if there's more useful information.

**Comment by idleberg** [comment]
One more question: do you set your environment variables system-wide or do you use VSCode's settings for the Terminal?

**Comment by wfmw445** [comment]
It’s a user-environment variable from Win10

**Comment by idleberg** [comment]
Please update to v3.30.0 and take note of [this chapter](https://github.com/idleberg/vscode-nsis#environment-variables)
