### ISSUE TITLE
Automatic build when opening and saving 

### ISSUE THREAD

**Issue by MacDisein** [idleberg/vscode-nsis#21]
Apparently for some time now the installer package is always built whenever I open or save an NSI script. This seems to be new or I didn't notice it.
I checked the settings for LINT, they are set to the default "Save PPO" - all other values don't change anything.

Is there an option to disable the behaviour, I have now delivered a corrupt installer twice.

**Comment by idleberg** [comment]
Thanks for reporting. Can you confirm that the problem is solved in the current `master` branch?

**Comment by MacDisein** [comment]
Solved in current master branch.

Thank you!
