### ISSUE TITLE
Build task order is wrong

### ISSUE THREAD

**Issue by zhiyuan823** [idleberg/vscode-nsis#26]
Dear author
I found error in args in build task json.
default settting is:
`
"args": [
        "${file}"
        "/V3",
      ]
`
verbosity settting has no any effect.
swap item of args order like this
`
"args": [
        "/V4",
        "${file}"
      ]
`
ok!

**Comment by idleberg** [comment]
Fixed in 8e04e173746a8df6d721affa63a27ed955f93338. Thanks for reporting this!
