### ISSUE TITLE
There are some garbled code in the complie output.

### ISSUE THREAD

**Issue by zhiyuan823** [idleberg/vscode-nsis#27]
Dear Author
Good day today!
When the script file encode is utf8 with bom and the script contains Chinese characters, click the 'complie' button and the command line output(/V4) log has garbled code.
like this
`
OutFile: "�����ļ�.exe"
Section: "Main" ->(0)
DetailPrint: "����һ��������Ϣ"
SectionEnd
`

test script for you
`
Unicode true
OutFile "测试文件.exe"

Section "Main" 0
    DetailPrint "这是一个测试信息"
SectionEnd
`
If I input "makensis / V4 test. NSI" directly in the terminal without using your software function, the output information output by the terminal is normal.

There are my context:
----------------------------------------------
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

NSIS config:
{
  "sizes": {
    "first_header": "28 bytes",
    "main_header": "300 bytes",
    "each_section": "2072 bytes",
    "each_page": "64 bytes",
    "each_instruction": "28 bytes"
  },
  "defined_symbols": {
    "__GLOBAL__": true,
    "NSIS_CHAR_SIZE": "1",
    "NSIS_COMPRESS_BZIP2_LEVEL": "9",
    "NSIS_CONFIG_COMPONENTPAGE": true,
    "NSIS_CONFIG_COMPRESSION_SUPPORT": true,
    "NSIS_CONFIG_CRC_SUPPORT": true,
    "NSIS_CONFIG_ENHANCEDUI_SUPPORT": true,
    "NSIS_CONFIG_LICENSEPAGE": true,
    "NSIS_CONFIG_PLUGIN_SUPPORT": true,
    "NSIS_CONFIG_SILENT_SUPPORT": true,
    "NSIS_CONFIG_UNINSTALL_SUPPORT": true,
    "NSIS_CONFIG_VISIBLE_SUPPORT": true,
    "NSIS_CPU": "x86",
    "NSIS_DEFAULT_LANG": "1033",
    "NSIS_FIX_COMMENT_HANDLING": true,
    "NSIS_IX86": 300,
    "NSIS_LOCKWINDOW_SUPPORT": true,
    "NSIS_MAX_INST_TYPES": 32,
    "NSIS_MAX_STRLEN": 1024,
    "NSIS_PACKEDVERSION": 0,
    "NSIS_PTR_SIZE": 4,
    "NSIS_SUPPORT_ACTIVEXREG": true,
    "NSIS_SUPPORT_BGBG": true,
    "NSIS_SUPPORT_CODECALLBACKS": true,
    "NSIS_SUPPORT_COPYFILES": true,
    "NSIS_SUPPORT_CREATESHORTCUT": true,
    "NSIS_SUPPORT_DELETE": true,
    "NSIS_SUPPORT_ENVIRONMENT": true,
    "NSIS_SUPPORT_EXECUTE": true,
    "NSIS_SUPPORT_FILE": true,
    "NSIS_SUPPORT_FILEFUNCTIONS": true,
    "NSIS_SUPPORT_FINDFIRST": true,
    "NSIS_SUPPORT_FNUTIL": true,
    "NSIS_SUPPORT_GETDLLVERSION": true,
    "NSIS_SUPPORT_GETFILETIME": true,
    "NSIS_SUPPORT_HWNDS": true,
    "NSIS_SUPPORT_INIFILES": true,
    "NSIS_SUPPORT_INTOPTS": true,
    "NSIS_SUPPORT_LANG_IN_STRINGS": true,
    "NSIS_SUPPORT_MESSAGEBOX": true,
    "NSIS_SUPPORT_MOVEONREBOOT": true,
    "NSIS_SUPPORT_NAMED_USERVARS": true,
    "NSIS_SUPPORT_REBOOT": true,
    "NSIS_SUPPORT_REGISTRYFUNCTIONS": true,
    "NSIS_SUPPORT_RENAME": true,
    "NSIS_SUPPORT_RMDIR": true,
    "NSIS_SUPPORT_SHELLEXECUTE": true,
    "NSIS_SUPPORT_STACK": true,
    "NSIS_SUPPORT_STANDARD_PREDEFINES": true,
    "NSIS_SUPPORT_STROPTS": true,
    "NSIS_SUPPORT_VERSION_INFO": true,
    "NSIS_UNICODE_MAKENSIS": true,
    "NSIS_VARS_SECTION": ".ndata",
    "NSIS_VERSION": "v3.06.1",
    "NSIS_WIN32_MAKENSIS": true,
    "NSISDIR": "d:\\Dropbox\\Tools\\Dev\\NSIS"
  }
}

**Comment by idleberg** [comment]
Note to self: Take a look at https://github.com/microsoft/vscode-arduino/commit/00d3fefcead1a95ec1b1ffbb32abc0f1b0a47a82

**Comment by idleberg** [comment]
I wish I could reproduce the issue, but the stdout prints the Chinese characters as expected on my English Windows 10 installation. That's not to say that I don't believe you, I simply can test this case and make improvements. However, could you check if the attached version fixes the issue? Use it to overwrite the lib folder of the extension.


[lib.zip](https://github.com/idleberg/vscode-nsis/files/6488371/lib.zip)

**Comment by zhiyuan823** [comment]
Dear author, thank you for your reply
I've run tests.Overwrite the copy of data you gave me to "VSCode\data\extensions\idleberg.nsis-3.41.0\lib\".Vscode was then restarted and tested.However, it is a pity that the content of Output is still confused in Chinese. 
Here is my complete output. I hope it will be helpful to you. Good luck!
----------------------------------------------
MakeNSIS v3.06.1 - Copyright 1999-2020 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.
Processing config: d:\Dropbox\Tools\Dev\NSIS\nsisconf.nsh
Processing default plugins: "d:\Dropbox\Tools\Dev\NSIS\Plugins\x86-ansi\*.dll"
 + Banner::destroy
 + Banner::getWindow
 + Banner::show
 + BgImage::AddImage
 + BgImage::AddText
 + BgImage::Clear
 + BgImage::Destroy
 + BgImage::Redraw
 + BgImage::SetBg
 + BgImage::SetReturn
 + BgImage::Sound
 + Dialer::AttemptConnect
 + Dialer::AutodialHangup
 + Dialer::AutodialOnline
 + Dialer::AutodialUnattended
 + Dialer::GetConnectedState
 + InstallOptions::dialog
 + InstallOptions::initDialog
 + InstallOptions::show
 + LangDLL::LangDialog
 + Math::Script
 + StartMenu::Init
 + StartMenu::Select
 + StartMenu::Show
 + System::Alloc
 + System::Call
 + System::Copy
 + System::Free
 + System::Get
 + System::Int64Op
 + System::Store
 + System::StrAlloc
 + TypeLib::GetLibVersion
 + TypeLib::Register
 + TypeLib::UnRegister
 + UserInfo::GetAccountType
 + UserInfo::GetName
 + UserInfo::GetOriginalAccountType
 + VPatch::GetFileCRC32
 + VPatch::GetFileMD5
 + VPatch::vpatchfile
 + advsplash::show
 + nsDialogs::Create
 + nsDialogs::CreateControl
 + nsDialogs::CreateItem
 + nsDialogs::CreateTimer
 + nsDialogs::GetUserData
 + nsDialogs::KillTimer
 + nsDialogs::OnBack
 + nsDialogs::OnChange
 + nsDialogs::OnClick
 + nsDialogs::OnNotify
 + nsDialogs::SelectFileDialog
 + nsDialogs::SelectFolderDialog
 + nsDialogs::SetRTL
 + nsDialogs::SetUserData
 + nsDialogs::Show
 + nsExec::Exec
 + nsExec::ExecToLog
 + nsExec::ExecToStack
 + nsProcess::_CloseProcess
 + nsProcess::_FindProcess
 + nsProcess::_KillProcess
 + nsProcess::_Unload
 + nsis7z::Extract
 + nsis7z::ExtractWithCallback
 + nsis7z::ExtractWithDetails
 + nsisdl::download
 + nsisdl::download_quiet
 + splash::show
 + textreplace::_FillReadBuffer
 + textreplace::_FindInFile
 + textreplace::_FreeReadBuffer
 + textreplace::_ReplaceInFile
 + textreplace::_Unload
 + unicode::FileAnsi2Unicode
 + unicode::FileUnicode2Ansi
 + unicode::FileUnicode2UTF8
 + unicode::UnicodeType
 + unicode::__FileAnsi2Unicode
 + unicode::__FileUnicode2Ansi
 + unicode::__FileUnicode2UTF8

!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "v:\Devcenter\BG\Test"

Processing script file: "v:\Devcenter\BG\Test\Test.nsi" (UTF8)
Unicode: true
Processing default plugins: "d:\Dropbox\Tools\Dev\NSIS\Plugins\x86-unicode\*.dll"
+ Banner::destroy
 + Banner::getWindow
 + Banner::show
 + BgImage::AddImage
 + BgImage::AddText
 + BgImage::Clear
 + BgImage::Destroy
 + BgImage::Redraw
 + BgImage::SetBg
 + BgImage::SetReturn
 + BgImage::Sound
 + Dialer::AttemptConnect
 + Dialer::AutodialHangup
 + Dialer::AutodialOnline
 + Dialer::AutodialUnattended
 + Dialer::GetConnectedState
 + InstallOptions::dialog
 + InstallOptions::initDialog
 + InstallOptions::make_unicode
 + InstallOptions::show
 + LangDLL::LangDialog
 + Math::Script
 + StartMenu::Init
 + StartMenu::Select
 + StartMenu::Show
 + System::Alloc
 + System::Call
 + System::Copy
 + System::Free
 + System::Get
 + System::Int64Op
 + System::Store
 + System::StrAlloc
 + TypeLib::GetLibVersion
 + TypeLib::Register
 + TypeLib::UnRegister
 + UserInfo::GetAccountType
 + UserInfo::GetName
 + UserInfo::GetOriginalAccountType
 + VPatch::GetFileCRC32
 + VPatch::GetFileMD5
 + VPatch::vpatchfile
 + advsplash::show
 + nsDialogs::Create
 + nsDialogs::CreateControl
 + nsDialogs::CreateItem
 + nsDialogs::CreateTimer
 + nsDialogs::GetUserData
 + nsDialogs::KillTimer
 + nsDialogs::OnBack
 + nsDialogs::OnChange
 + nsDialogs::OnClick
 + nsDialogs::OnNotify
 + nsDialogs::SelectFileDialog
 + nsDialogs::SelectFolderDialog
 + nsDialogs::SetRTL
 + nsDialogs::SetUserData
 + nsDialogs::Show
 + nsExec::Exec
 + nsExec::ExecToLog
 + nsExec::ExecToStack
 + nsProcess::_CloseProcess
 + nsProcess::_FindProcess
 + nsProcess::_KillProcess
 + nsProcess::_Unload
 + nsis7z::Extract
 + nsis7z::ExtractWithCallback
 + nsis7z::ExtractWithDetails
 + nsisdl::download
 + nsisdl::download_quiet
 + splash::show
 + textreplace::_FillReadBuffer
 + textreplace::_FindInFile
 + textreplace::_FreeReadBuffer
 + textreplace::_ReplaceInFile
 + textreplace::_Unload
 + unicode::FileAnsi2Unicode
 + unicode::FileUnicode2Ansi
 + unicode::FileUnicode2UTF8
 + unicode::UnicodeType
 + unicode::__FileAnsi2Unicode
 + unicode::__FileUnicode2Ansi
 + unicode::__FileUnicode2UTF8

OutFile: "�����ļ�.exe"
Section: "Main" ->(0)
DetailPrint: "����һ��������Ϣ"
SectionEnd

Processed 1 file, writing output (x86-unicode):
Processing pages... Done!
Removing unused resources... Done!
Generating language tables... Done!

Output: "v:\Devcenter\BG\Test\�����ļ�.exe"
Install: 1 page (64 bytes), 1 section (2072 bytes), 2 instructions (56 bytes), 104 strings (564 bytes), 1 language table (194 bytes).

Using zlib compression.

EXE header size:               37888 / 39424 bytes
Install code:                    490 / 3342 bytes
Install data:                      0 / 0 bytes
CRC (0x445105CF):                  4 / 4 bytes

Total size:                    38382 / 42770 bytes (89.7%)

**Comment by idleberg** [comment]
As I've mentioned before, your example script with Chinese characters works fine on my (English) Windows 10 / macOS versions of VSCode. It's probably a configuration issue. I can't do anything, unless I can reproduce the issue. Sorry!

**Comment by zhiyuan823** [comment]
Thank you for your reply. I will install an English version of Windows10 and try again.

**Comment by zhiyuan823** [comment]
Thank you for your reply. I will install an English version of Windows10 and try again.

**Comment by zhiyuan823** [comment]
I installed the latest Win10 which is English version in the virtual machine, version: 21H1, OS Build: 19043.928.
After testing, the problem still exists.  By the way, My vscode is english version.
I think it might be the script file problem.If possible, I would like to email the original script file to you, hopefully it will be helpful for testing.If possible, could you give me an email address?thank you
----------
OutFile: "????.exe"
Section: "Main" ->(0)
DetailPrint: "????????"
SectionEnd
------

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

NSIS INFO:
{
  "sizes": {
    "first_header": "28 bytes",
    "main_header": "300 bytes",
    "each_section": "2072 bytes",
    "each_page": "64 bytes",
    "each_instruction": "28 bytes"
  },
  "defined_symbols": {
    "__GLOBAL__": true,
    "NSIS_CHAR_SIZE": "1",
    "NSIS_COMPRESS_BZIP2_LEVEL": "9",
    "NSIS_CONFIG_COMPONENTPAGE": true,
    "NSIS_CONFIG_COMPRESSION_SUPPORT": true,
    "NSIS_CONFIG_CRC_SUPPORT": true,
    "NSIS_CONFIG_ENHANCEDUI_SUPPORT": true,
    "NSIS_CONFIG_LICENSEPAGE": true,
    "NSIS_CONFIG_LOG": true,
    "NSIS_CONFIG_PLUGIN_SUPPORT": true,
    "NSIS_CONFIG_SILENT_SUPPORT": true,
    "NSIS_CONFIG_UNINSTALL_SUPPORT": true,
    "NSIS_CONFIG_VISIBLE_SUPPORT": true,
    "NSIS_CPU": "x86",
    "NSIS_DEFAULT_LANG": "1033",
    "NSIS_FIX_COMMENT_HANDLING": true,
    "NSIS_IX86": 300,
    "NSIS_LOCKWINDOW_SUPPORT": true,
    "NSIS_MAX_INST_TYPES": 32,
    "NSIS_MAX_STRLEN": 1024,
    "NSIS_PACKEDVERSION": 0,
    "NSIS_PTR_SIZE": 4,
    "NSIS_SUPPORT_ACTIVEXREG": true,
    "NSIS_SUPPORT_BGBG": true,
    "NSIS_SUPPORT_CODECALLBACKS": true,
    "NSIS_SUPPORT_COPYFILES": true,
    "NSIS_SUPPORT_CREATESHORTCUT": true,
    "NSIS_SUPPORT_DELETE": true,
    "NSIS_SUPPORT_ENVIRONMENT": true,
    "NSIS_SUPPORT_EXECUTE": true,
    "NSIS_SUPPORT_FILE": true,
    "NSIS_SUPPORT_FILEFUNCTIONS": true,
    "NSIS_SUPPORT_FINDFIRST": true,
    "NSIS_SUPPORT_FNUTIL": true,
    "NSIS_SUPPORT_GETDLLVERSION": true,
    "NSIS_SUPPORT_GETFILETIME": true,
    "NSIS_SUPPORT_HWNDS": true,
    "NSIS_SUPPORT_INIFILES": true,
    "NSIS_SUPPORT_INTOPTS": true,
    "NSIS_SUPPORT_LANG_IN_STRINGS": true,
    "NSIS_SUPPORT_MESSAGEBOX": true,
    "NSIS_SUPPORT_MOVEONREBOOT": true,
    "NSIS_SUPPORT_NAMED_USERVARS": true,
    "NSIS_SUPPORT_REBOOT": true,
    "NSIS_SUPPORT_REGISTRYFUNCTIONS": true,
    "NSIS_SUPPORT_RENAME": true,
    "NSIS_SUPPORT_RMDIR": true,
    "NSIS_SUPPORT_SHELLEXECUTE": true,
    "NSIS_SUPPORT_STACK": true,
    "NSIS_SUPPORT_STANDARD_PREDEFINES": true,
    "NSIS_SUPPORT_STROPTS": true,
    "NSIS_SUPPORT_VERSION_INFO": true,
    "NSIS_UNICODE_MAKENSIS": true,
    "NSIS_VARS_SECTION": ".ndata",
    "NSIS_VERSION": "v3.02.1",
    "NSIS_WIN32_MAKENSIS": true,
    "NSISDIR": "C:\\NSIS"
  }
}
