### ISSUE TITLE
Colapse all

### ISSUE THREAD

**Issue by dpalat** [idleberg/vscode-nsis#3]
Hi!, your plugin is awasomem thanks!

Can you tell me how colapse all functions and macro in vs code with your plugin in  nsh or nsi files?

thanks a lot!

**Comment by idleberg** [comment]
That's actually a core feature of Visual Studio Code

1. Open the command palette
2. Run ”Fold All” / ”Unfold All”

The shortcuts are mentioned next to each command

**Comment by dpalat** [comment]
You are the best!

regards!
