### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by systempal** [idleberg/vscode-nsis#30]
I have a project with many small .nsh in a subfolder.

If i call a macro that is not in the current file like for example `${PSExecCommandL} "Enable-RemoteDesktop"`, the linter report to me a problem like "Invalid command...."

![2021-06-18_212719](https://user-images.githubusercontent.com/19501068/122608184-11e9f700-d07c-11eb-9e98-a3c3fa624f78.png)

Is there a way to solve this ?

An options to exclude some files from linting is enought to me.

Tnks,
Simone.

**Comment by idleberg** [comment]
Why don't you simply include the macro? As far as I know, the compiler is smart enough to avoid duplication macro declarations.

I will consider an exclude option, but it might take some time until I can give it a shot.

**Comment by systempal** [comment]
Well,
there are many files and nested macros. Perarph the compiler is not smart like you suppose...

Tnks you for your effort!

**Comment by idleberg** [comment]
If you're feeling adventurous, you could give the latest `master` a try and see how it works for you. This version has a new option `nsis.diagnostics.excludedFiles`. Pollow [these steps](https://github.com/idleberg/vscode-nsis#clone-repository) to install the latest version using Git.

**Comment by systempal** [comment]
![2021-06-19_191746](https://user-images.githubusercontent.com/19501068/122650439-4a004100-d133-11eb-90a1-3b2619b56635.png)

**Comment by idleberg** [comment]
Will put out a new release next week. Thanks for reporting & testing!

**Comment by systempal** [comment]
Cool, tnks to you.
