### ISSUE TITLE
Can I ask you to apply for Unicode?

### ISSUE THREAD

**Issue by SMKim94** [idleberg/vscode-nsis#31]
## Summary

Request for UTF-8 support.

## Motivation

As far as I know, Unicode support is available from NSIS 3.0.
However, when using this plug-in, the Unicode string is still unavailable.
The "Argument" option can be set, but the compilation cannot proceed due to the occurrence of the "Bad text encoding" error during the error check step before compilation.
The code below is the code I wrote.
```
Unicode true
OutFile "한글 테스트.exe"
Section "section_name" section_index_output

SectionEnd
```

## Describe alternatives you've considered

If the Unicode attribute at the top of the code is written as true, I hope it does not cause an encoding error for the Unicode string.
And I would like you to add the attributes corresponding to /INPUTCHARSET and /OTPUTCHARSET Argument with the vcode extension setting.

## Additional context

- When I use this vcode extension
![image](https://user-images.githubusercontent.com/42730517/143666053-fb5979ae-d58e-4a6a-9cb8-330ad3c66a5d.png)

- When I directly run makensis.exe
![image](https://user-images.githubusercontent.com/42730517/143666043-efd7fb45-2331-4305-84e3-8239eafc251d.png)

**Comment by idleberg** [comment]
Could you please attach the exact script from the screenshot. I want to make sure I'm using the same file with the same encoding etc. Thanks!

**Comment by SMKim94** [comment]
Script
```
Unicode true
OutFile "한글 테스트.exe"
Section "section_name" section_index_output

SectionEnd
```
The file encoding was UTF-8. And I installed NSIS 3.08.

![image](https://user-images.githubusercontent.com/42730517/143876299-aadf99f6-181d-48f3-aff0-dda763b7d115.png)

**Comment by idleberg** [comment]
The script compiles fine for me, but I'm using an English version of Windows 10. Also, attaching the script as you saved it might give more insights than pasting its contents.

I suspect that this is the same issue as #27 and that the error happens along the way from the script to passing it to the compiler. If you're willing into investing some time into this, I could come up with a couple of tests to identify the issue.

**Comment by SMKim94** [comment]
I'm sorry for the late reply.
If you tell me how to test it, I'll try it.
For your information, my operating system is the Korean version of Windows 10 Home.

**Comment by SMKim94** [comment]
> ## Summary
> Request for UTF-8 support.
> 
> ## Motivation
> As far as I know, Unicode support is available from NSIS 3.0. However, when using this plug-in, the Unicode string is still unavailable. The "Argument" option can be set, but the compilation cannot proceed due to the occurrence of the "Bad text encoding" error during the error check step before compilation. The code below is the code I wrote.
> 
> ```
> Unicode true
> OutFile "한글 테스트.exe"
> Section "section_name" section_index_output
> 
> SectionEnd
> ```
> 
> ## Describe alternatives you've considered
> If the Unicode attribute at the top of the code is written as true, I hope it does not cause an encoding error for the Unicode string. And I would like you to add the attributes corresponding to /INPUTCHARSET and /OTPUTCHARSET Argument with the vcode extension setting.
> 
> ## Additional context
> * When I use this vcode extension
>   ![image](https://user-images.githubusercontent.com/42730517/143666053-fb5979ae-d58e-4a6a-9cb8-330ad3c66a5d.png)
> * When I directly run makensis.exe
>   ![image](https://user-images.githubusercontent.com/42730517/143666043-efd7fb45-2331-4305-84e3-8239eafc251d.png)

**Comment by idleberg** [comment]
> If you tell me how to test it, I'll try it.

If you could, here's a little test to see whether compiling the script via a NodeJS wrapper works or if it produces the same result.

1. Install NodeJS
2. Create a folder and run `npm init -y` inside
3. Run `npm install makensis` in that folder
4. Run the following script using `node test.js`

```test.js
import * as NSIS from 'makensis';

(async () => {
	  try {
	      let output = await NSIS.compile('test.nsi');
	      console.log('Compiler output:', output);
	  } catch (error) {
	      console.error(error);
	  }
})();
```

**Comment by idleberg** [comment]
> And I would like you to add the attributes corresponding to /INPUTCHARSET and /OTPUTCHARSET Argument with the vcode extension setting.

I missed this bit before. You can already specify custom parameters in the extension settings:

**Example**

![Screenshot 2021-12-16 at 22 52 20](https://user-images.githubusercontent.com/1504938/146454506-471e1840-f3aa-469b-9b27-7939ae9fcfe6.png)

**Comment by SMKim94** [comment]
Wow, Very Thanks. It works. 
I don't know why bad text encoding occurs, but compilation is very good.
Sorry, In the past, I wrote Arguments in a row, so it seems that the compilation was not possible.
![20211218_result01](https://user-images.githubusercontent.com/42730517/146567279-87985d6a-ab41-459e-ad69-cb5c36b593aa.png)
