### ISSUE TITLE
[warning message] can very confuse snippet variables and snippet placeholders.

### ISSUE THREAD

**Issue by famibee** [idleberg/vscode-nsis#34]
It's not a bug, but it gives a warning.
While creating the VS Code extension, the following message was displayed when opening DevTools. Share information.

　バグではないが、警告が出ています。
　VSCode 拡張機能作成中、DevTools を開くと下記のメッセージが出ていた。情報共有します。

[idleberg.nsis]: 拡張機能 'nsis' の 1 つまたは複数のスニペットは、スニペット変数とスニペット プレース ホルダーを混乱させる可能性が非常にあります。 (詳細については、 https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax を参照してください)

 _logMessageInConsole | @ | workbench.desktop.main.js:3067

<img width="800" alt="スクリーンショット 2022-03-18 03-18 金 22 57" src="https://user-images.githubusercontent.com/16816132/159016658-c9d8a70f-c9a7-4169-80fd-16f944a6255f.png">

**Comment by idleberg** [comment]
Thanks for reporting the issue. Since I don't read Japanese, I have used Deepl to translate the warning. To me, it reads like you have created a user snippet that produces this warning.

**Comment by famibee** [comment]
As you said, there is a warning in [One or more snippets for the extension'nsis']. If you debug some other extension and open DevTools, you may get the same message.

おっしゃるとおり、【拡張機能 'nsis' の 1 つまたは複数のスニペット】に警告が出ています。なにか別の拡張機能をデバッグし、DevTools を開くと同じメッセージが出るかも知れません。
