### ISSUE TITLE
Show compiler flags does not display hex numbers

### ISSUE THREAD

**Issue by sredna** [idleberg/vscode-nsis#36]
### Description

"Show compiler flags" command does not display hex numbers, specifically NSIS_PACKEDVERSION which is in HEX for display purposes. If whatever you are doing to parse these fails, just display it as a string.

**Expected behavior:**

Display "NSIS_PACKEDVERSION": 0x308000

**Actual behavior:**

Displays "NSIS_PACKEDVERSION": 0

**Reproduces how often:**

100%

### Versions

Extension version v3.49.0

**Comment by idleberg** [comment]
Thank you, Anders. I have fixed this in the [node-makensis](https://www.npmjs.com/package/makensis) repository and will bump the VSCode extension in the next couple of days.

**Comment by sredna** [comment]
> Thank you, Anders. I have fixed this in the [node-makensis](https://www.npmjs.com/package/makensis) repository and will bump the VSCode extension in the next couple of days.

The fix does not seem correct to me? You are forcing base 10 when calling parseInt.

**Comment by idleberg** [comment]
fixed in 3.50.1
