### ISSUE TITLE
Option for MakeNSIS default verbosity

### ISSUE THREAD

**Issue by sredna** [idleberg/vscode-nsis#37]
There should be an option to use the compilers default verbosity. MakeNSIS without -v uses a verbosity that is not possible to achieve with the parameter. Specifically, it is -v3 but with the version/"logo".

**Comment by idleberg** [comment]
Thanks for reporting the issue. I don't think I understand what you mean with the following to sentences:

- MakeNSIS without -v uses a verbosity that is not possible to achieve with the parameter
- Specifically, it is -v3 but with the version/"logo".

Maybe you can rephrase and give more detail?

**Comment by sredna** [comment]
When you run MakeNSIS without a -v parameter then the result is that it will first print the version/"logo" and then switch to `!verbose 3` before processing the input files. You don't see this in MakeNSISW because it forces -v4. This "feature" was added early in v3.x because it was decided that -v4 (the old default) was too much when compiling in a console.

**Comment by idleberg** [comment]
Added in v3.50.0
