### ISSUE TITLE
When compiling there's no feedback

### ISSUE THREAD

**Issue by hahn-kev** [idleberg/vscode-nsis#4]
When you Save and Compile via the Command palette there's no feedback on compile progress, if I could see the cli output or something similar that would be great, it seems like there's no way of knowing if it crashes or if it's just taking a long time.

**Comment by idleberg** [comment]
Good suggestion, looking into it

**Comment by idleberg** [comment]
Take a look at the current master. It works for me, but I haven't been able to test on Windows yet.

**Comment by idleberg** [comment]
Please taake a look at [v2.3.0](https://github.com/idleberg/vscode-nsis/releases/tag/2.3.0)!

**Comment by hahn-kev** [comment]
That works great thanks!
