### ISSUE TITLE
Some Highlightling display error

### ISSUE THREAD

**Issue by wbsdty331** [idleberg/vscode-nsis#41]
### Description

Some Highlightling display error.

### Steps to Reproduce

1. Open Visual Studio and install nsis extension
2. open a nsi file 

**Expected behavior:**

Some settings value (such as `true|false`) display error.
![image](https://user-images.githubusercontent.com/4280572/175206712-59670ba5-4628-4c8c-bda6-624390bbcf85.png)
By the way, the new option : `Target` is not highlighted. 
It can control installer target so you can build 32 or 64bit, ansi or unicode installer.
![image](https://user-images.githubusercontent.com/4280572/175206907-5b2c3c98-a5ee-4149-8a95-8470fd8b8a99.png)

**Actual behavior:**
The code is displayed correctly.
![image](https://user-images.githubusercontent.com/4280572/175207308-4cfb51aa-be24-48a7-967a-07e68646f299.png)

**Reproduces how often:**

### Versions

```
macOS 11.6.7

VSCode Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0
```

**Comment by idleberg** [comment]
Are you using a fork of NSIS or a nightly version? This doesn‘t seem to be covered by the official documentation.

**Comment by wbsdty331** [comment]
No, I use official version.
![image](https://user-images.githubusercontent.com/4280572/175295848-8c03766d-8b44-469a-82d7-79e446466077.png)

From: https://sourceforge.net/p/nsis/feature-requests/549/ Andres said:

> Makensis v3 (32 and 64 bit) can produce 32 and 64 bit installers if you use the undocumented "Target" instruction but since there is no official 64-bit build yet you have to compile the stubs and plugins as 64-bit yourself or get them from someone.

NSIS Windows Version doesn't include 64bit library, you should build it by yourself or extract them from Linux Package such as Debian or ubuntu. You need `Stubs` and `Include` Folder, they all have amd64 build file.

![image](https://user-images.githubusercontent.com/4280572/175295663-14dbf87b-63f3-4c12-8aa8-7ce548532cb1.png)

then add `Target amd64-unicode` in your nsis script file, then you will get a x64 build. The premise is you just use official plugins:
![image](https://user-images.githubusercontent.com/4280572/175296191-4a5fbc19-0922-4a5c-9f4d-db961ba7ac88.png)

**Comment by idleberg** [comment]
Should have been fixes in the latest version

**Comment by wbsdty331** [comment]
nice work, Thanks!
