### ISSUE TITLE
Verbosity setting is not handled correctly

### ISSUE THREAD

**Issue by systempal** [idleberg/vscode-nsis#42]
Steps to Reproduce

1. Open Settings.
2. Change Verbosity to other than "3".
3. Save.
4. Re-Open settings.

Also, even with default settings there is no output.

![Immagine 2022-08-18 231045](https://user-images.githubusercontent.com/19501068/185496102-1b64dc6b-880e-4099-9153-ff8d7cbfa974.png)

**Comment by systempal** [comment]
And there's the fix:

package.json

change :
        "nsis.compiler.verbosity": {
          "type": "number",
          "enum": [
            "-1",
            "0",
            "1",
            "2",
            "3",
            "4"
          ],


with:
       "nsis.compiler.verbosity": {
          "type": "number",
          "enum": [
            -1,
            0,
            1,
            2,
            3,
            4
          ],

**Comment by idleberg** [comment]
Thanks, fixed in v3.51.3

**Comment by systempal** [comment]
> 

Thanks!
