### ISSUE TITLE
Cannot read properties of undefined (reading 'stdout')

### ISSUE THREAD

**Issue by Anton-V-K** [idleberg/vscode-nsis#43]
The extension fails to build the script opened in VSCode 1.73.1 - it shows the error popup like "Compilation failed, see output for details", but the ouput window is empty.
Opening the extension page reveals the problem on the **Runtime Status** tab:
```
Cannot read properties of undefined (reading 'stdout')
```
The path to `makensis` is specified as `"C:\Program Files (x86)\NSIS\makensis.exe"` (it exists there)
![image](https://user-images.githubusercontent.com/20116984/208077131-2b0a7819-8f17-4705-8add-0ae2d7814052.png)

The content of `C:\Users\%USERNAME%\AppData\Roaming\Code\User\settings.json`:
```
{
    "workbench.colorTheme": "Default Light+",
    "nsis.compiler.pathToMakensis": "\"C:\\Program Files (x86)\\NSIS\\makensis.exe\""
}
```
VSCode info:
```
Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
```
OS: Windows 10 21H1 (64-bit)

BTW an attemp to show NSIS version (with `NSIS: Show Version`) results in an error:
![image](https://user-images.githubusercontent.com/20116984/208075908-ae1bf111-8910-4d62-a7ad-d2a80d38a335.png)

Probably the path is handled incorrectly?

Removing leading and trailing double quotes solves the problem:
```
{
    "workbench.colorTheme": "Default Light+",
    "nsis.compiler.pathToMakensis": "C:\\Program Files (x86)\\NSIS\\makensis.exe"
}
```
See also #25

**Comment by beibeibeibei2022** [comment]
[microsoft docs - Naming Conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) 🡸🢜🢜🢜 Microsoft's Windows system hates double quotes.
For questions about double quotes, please contact Microsoft.
<code>A file name can't contain any of the following characters:</code> 🡸🢜🢜🢜 Google it.
So, see [readme](https://github.com/idleberg/vscode-nsis#makensis), just copy it.
