### ISSUE TITLE
Error on EndSwitch statement

### ISSUE THREAD

**Issue by fkamming** [idleberg/vscode-nsis#44]
Using the LogicLib Switch ... EndSwitch statements the editor always reports an error on the EndSwitch line.

![image](https://user-images.githubusercontent.com/13777613/213646573-71fd6f5d-1498-491b-b32a-eaa77274991b.png)

No problems reported in makensis. Therefore, I suspect the issue is in vscode-nsis.

NSIS: 3.08
Visual Studio Code: 1.74.3
vscode-nsis: 3.52.0

**Comment by idleberg** [comment]
This error is also returned from `makensis`. The reason why you don't see this when compiling the installer is the `-SAFEPPO` that's used by default in diagnostics mode. You can change this in the extension settings (see `nsis.diagnostics.preprocessMode`).

**Comment by idleberg** [comment]
I have created an issue on [SourceForge](https://sourceforge.net/p/nsis/bugs/1291/) and intend to change the default to `PPO`. Closing this.
