### ISSUE TITLE
Do the NSIS_APP_* defined variables in .env files work?

### ISSUE THREAD

**Issue by AurelianTimu** [idleberg/vscode-nsis#45]
Hello,

Apparently, support for ''magic" environment variables was removed.
Having the following key/value definition in a `.env` file near the `.nsi` script does not work.
`NSIS_APP_ENVIRONMENT="development"` or `NSIS_APP_ENVIRONMENT=development`

Script usage:
`!define ENVIRONMENT ${NSIS_APP_ENVIRONMENT}`

Output log:
`warning 6000: unknown variable/constant "{NSIS_APP_ENVIRONMENT}" detected`

Can you please confirm this, and maybe update the README?

**Comment by idleberg** [comment]
You're implying that it worked in an older version, which one was it? There haven't been any significant changes in this extension in the past 6 months (or even longer), so I'm having some doubts.

Also, the support for environment variables has some restrictions. The extension does not watch for changes on your `.env` file and expects it to be in place at launch time.

**Comment by AurelianTimu** [comment]
Good point, I don't know if it worked in an older version.
Just started to use this extension.

I was browsing through the code before creating this issue and I saw this change: 78ca7e07fd0dbec638804dc708553f1d45716279
After this change, it does not appear there is much usage of the `.env` files as far as I can tell.

**Comment by idleberg** [comment]
> I was browsing through the code before creating this issue and I saw this change: https://github.com/idleberg/vscode-nsis/commit/78ca7e07fd0dbec638804dc708553f1d45716279

This extension makes use of the `makensis` Node module which already supports loading environment variables. So all this commit does is removing redundant code.

I'm using the following to test the functionality and it seems to work for me (tested on macOS 10.15 and Windows 11)

**Files**

```env
# .env
NSIS_APP_TEST=Hello World
```

```nsis
# demo.nsi
OutFile demo.exe

!error "Env: ${NSIS_APP_TEST}"

Section
SectionEnd
```

**makensis log**

```
MakeNSIS v3.08 - Copyright 1999-2021 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Command line defined: "NSIS_APP_TEST=Hello World"

Processing script file: "/Users/idleberg/demo.nsi" (UTF8)

!error: Env: Hello World
Error in script "/Users/idleberg/demo.nsi" on line 5 -- aborting creation process
```

If you can provide further insights (or a zipped example), I can invest some more time to see why it's not working for you.
