### ISSUE TITLE
New telemetry functionality should have a mention in the docs

### ISSUE THREAD

**Issue by ThubLives** [idleberg/vscode-nsis#48]
It seems that since 4.2.0, telemetry is being collected.  I would be nice to have a mention in the README, as well as whether and how it can be disabled.

**Comment by idleberg** [comment]
I agree, that‘s an excellet idea. I will add a chapter on *why* telemetry was added and which specific data is sent. However, I won‘t be able to until I get back home next weekend.

**TL;DR**

The extension follows the global telemetry setting, which is the default behaviour of Microsoft‘s telemetry NodeJS package. However, I added a setting that allows disabling telemetry even when the global setting allows it.
