### ISSUE TITLE
Feature Request: Formatter

### ISSUE THREAD

**Issue by agjs** [idleberg/vscode-nsis#8]
Hi there :-). First of all, thanks for building the extension, great effort.

I'm wondering, do you have any plans to integrate a formatter? Indenting stuff manually often can become cumbersome and would be awesome to have a formatter :)!

Cheers

**Comment by idleberg** [comment]
A formatter would be awesome, but there currently exists none I could use. Most other features in this extension make use of `makensis`'s features or existing third-party tools.
