### ISSUE TITLE
Why release version 3.16.5 is so big?

### ISSUE THREAD

**Issue by lychichem** [idleberg/vscode-nsis#9]
The size of version 3.16.5 is 65MB, but version 3.16.3 is only 241KB. I really wonder if something is mistakenly added into the package.

**Comment by idleberg** [comment]
Looks like `node_modules/typescript`, at 44 MB, is responsible for this

Related:

https://github.com/microsoft/TypeScript/issues/27891

**Comment by idleberg** [comment]
The reason was probably a different one, but v3.17.0 is much smaller
